version: "3"
services:
  database:
    image: mysql
    container_name: about_runnings_db
    environment:
      - MYSQL_DATABASE=about_runnings_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - about_runnings_network_01
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: aboutrunnings/aboutrunnings:latest
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    container_name: app_test01
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/about_runnings_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - about_runnings_network_01
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
networks:
  about_runnings_network_01:
